version: '3.8'  # Версия схемы Compose

services:
  web:  # Название сервиса
    image: nginx:alpine  # Используем официальный образ Nginx
    ports:
      - "8080:80"  # Пробрасываем порт 8080 хоста → 80 контейнера