version: "3.8"

services:
  fastapi:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./app:/app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    depends_on:
      - fastapi
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --non-interactive --agree-tos -d ${DOMAIN} -m ${EMAIL}
    restart: unless-stopped

volumes:
  certbot-www:
  certbot-conf: